version: '3.1'

services:
  accountservice:
    image: paramarporn/dhtest
    ports:
      - 8080:8080
    build:
      context: ./accountservice
    container_name: testservice
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
